# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "YOUR_SHOPIFY_API_KEY"
name = "ReviewReel"
application_url = "https://YOUR_TUNNEL_URL"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks"

[access_scopes]
scopes = "read_products,read_orders"

[auth]
redirect_urls = [ "https://YOUR_TUNNEL_URL/auth/callback" ]

[pos]
embedded = false
